### ISSUE TITLE
Possible SQL injection issue

### ISSUE THREAD

**Issue by otatarintseva** [emeneo/moodle-enrol_waitlist#3]
Hello,
We want to inform you about the possible security issue in the enrol_waitlist plugin. It uses directly $_POST variable. In some places and it could open the door for SQL injection attacks. For example:
print.php lines 17-33

**Comment by Flottertotte** [comment]
Hello, Thank you very much for finding and reporting this! The issue has been fixed, please take a look! In case you find any other issue, please let us know.

**Comment by otatarintseva** [comment]
Hello,
Thank you for response and implemented changes. Unfortunately, the function data_submitted() does not resolve the issue. It still allows the malicious user to make SQL injection attack.
Another strange thing is course_marking table calling in print.php - it looks like the table does not exist. Moreover, it looks like the print.php file is not in use.

**Comment by Flottertotte** [comment]
Thanks a lot for the feedback. You are right, the print.php is not in use, it went there in the course of adding functionality from another plugin.  I already removed it.
But concerning the SQL injection problem:  in the latest version it should not be possible anymore, please see the attached picture. 

![download](https://user-images.githubusercontent.com/7721497/47959419-a663d000-e01e-11e8-9dda-d4ce05d25eeb.jpg)

It would be great if you could take a look and give a feedack
